apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
metadata:
  name: k206
namespace: default
commonLabels:
  app.cd22.dltdojo/name: k206
namePrefix: stag-

resources:
  - ../base

configMapGenerator:
  - name: cm-init-sh
    behavior: replace
    files:
      - git-init.sh
      - vscode-init.sh
