[package]
name = "zk101"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies]
wasm-bindgen = "0.2"
miden-prover = { version = "0.2.0", default-features = false}
miden-assembly = { version = "0.2.0", default-features = false}

[workspace]