apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
#
# https://github.com/istio-ecosystem/authservice/tree/master/bookinfo-example/authservice
#
configMapGenerator:
- name: authservice
  files:
  - config.json
resources:
  - authservice.yaml
  - authz.yaml
