apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: istio-metrics
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
  labels:
    version: v1
spec:
  syncPolicy:
    automated: {}
  destination:
    server: {{ .Values.spec.destination.server }}
  source:
    path: istio-metrics
    repoURL: {{ .Values.spec.source.repoURL }}
    targetRevision: {{ .Values.spec.source.targetRevision }}
  project: default
