version: "3.8"
services:
  box1:
    image: busybox:1.35.0
    command:
      - /bin/sh
      - -c
      - |
        cat <<\EOOF > index.html
        <html>
        <head><title>GoEP-IGoEP 2022</title></head>
        <body><p>HELLO Busybox Httpd</p></body>
        </html>
        EOOF
        # 找優勢策略或均衡的坑
        busybox httpd -fv -p 3000
    ports:
      - "8301:3000"
  box2:
    image: busybox:1.35.0
    command:
      - /bin/sh
      - -c
      - |
        mkdir /www /www/cgi-bin /www/etc
        cat <<\EOOF > /www/etc/passwd.html
        <html>
        <head>
        <title>GoEP-IGoEP 2022</title>
        <meta http-equiv="Refresh" content="0; url=/cgi-bin/index.sh?path=/etc/passwd" />
        </head>
        <body>挖形成優勢策略或均衡的坑</body>
        </html>
        EOOF
        # 
        # NOTE: $$ to escape the $ dollar sign in a docker compose file
        # 
        cat <<\EOOF > /www/cgi-bin/index.sh
        #!/bin/sh
        echo "Content-Type: text/html"
        echo ""
        echo "$$QUERY_STRING"
        THEPATH=$(echo "$$QUERY_STRING" | cut -d "=" -f 2)
        echo "$$THEPATH"
        cat "$$THEPATH"
        EOOF
        cat <<\EOOF > /www/cgi-bin/foo.sh
        #!/bin/sh
        echo "Status: 302 Redirect"
        echo "Location: /cgi-bin/index.sh?path=/etc/passwd"
        echo
        echo ""
        EOOF
        chmod 700 /www/cgi-bin/*.sh
        cd /www
        busybox httpd -fv -p 3000
    ports:
      - "8302:3000"
  curl101:
    image: curlimages/curl:7.86.0
    command:
      - sh
      - -c
      - |
        curl -sv --retry 5 --retry-all-errors http://box1:3000/etc/passwd
        #
        # browser and curl diff  http://box2:3000/etc/passwd.html
        # 
        curl -sv --retry 5 --retry-all-errors http://box2:3000/etc/passwd.html
        curl -sv http://box2:3000/cgi-bin/index.sh?path=/etc/passwd
        curl -svL http://box2:3000/cgi-bin/foo.sh
