apiVersion: v1
kind: Namespace
metadata:
  name: napp2022
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: napp2022
  labels:
    app: napp2022
spec:
  selector:
    matchLabels:
      app: napp2022
  template:
    metadata:
      labels:
        app: napp2022
    spec:
      containers:
        - name: napp
          image: napp
          args:
            - srv
          resources: {}
