apiVersion: batch/v1
kind: Job
metadata:
  name: git-repo-push
spec:
  template:
    metadata:
      labels:
        sidecar.istio.io/inject: "false"
    spec:
      containers:
      - name: git-repo-push
        image: kg8s-local/kctl:v21.12.1
        command: ["bash"]
        args:
          - -c
          - |
            echo $(date)
            ls -al /sys-seed
            echo "Init sys-seed repo"
            gitea_repo_api=http://gitops-admin:1fJyRTcesfe2e67df123XYZ@gitea-http.gitea.svc.cluster.local:3000/api/v1/user/repos
            curl -kv POST $gitea_repo_api -H 'accept: application/json' -H 'Content-Type: application/json' \
              -d '{ "name": "sys-seed" }'
            cd /sys-seed
            echo
            echo "push sys-seed repo"
            git init
            git remote add origin http://gitops-admin:1fJyRTcesfe2e67df123XYZ@gitea-http.gitea.svc.cluster.local:3000/gitops-admin/sys-seed.git
            git config user.email "alice@example.local"
            git config user.name "Alice"
            git add .
            git commit -m "push sys-seed content"
            git push -u origin master
      restartPolicy: Never
  backoffLimit: 2
