apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    dltdojo.org/cd23: dafu101
  name: ing101-traefik-whoamiv1.8.7-c87281e2
spec:
  minReadySeconds: 0
  progressDeadlineSeconds: 600
  replicas: 2
  selector:
    matchLabels:
      cdk8s.io/metadata.addr: ing101-traefik-whoamiv1.8.7-c845b3be
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        cdk8s.io/metadata.addr: ing101-traefik-whoamiv1.8.7-c845b3be
        dltdojo.org/cd23: dafu101
    spec:
      automountServiceAccountToken: false
      containers:
        - image: traefik/whoami:v1.8.7
          imagePullPolicy: Always
          name: main
          ports:
            - containerPort: 80
          resources:
            limits:
              cpu: 1500m
              memory: 2048Mi
            requests:
              cpu: 1000m
              memory: 512Mi
          securityContext:
            allowPrivilegeEscalation: false
            privileged: false
            readOnlyRootFilesystem: false
            runAsNonRoot: false
          startupProbe:
            failureThreshold: 3
            tcpSocket:
              port: 80
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      securityContext:
        fsGroupChangePolicy: Always
        runAsNonRoot: true
      setHostnameAsFQDN: false
---
apiVersion: v1
kind: Service
metadata:
  labels:
    dltdojo.org/cd23: dafu101
  name: dev101
spec:
  externalIPs: []
  ports:
    - port: 80
  selector:
    cdk8s.io/metadata.addr: ing101-traefik-whoamiv1.8.7-c845b3be
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    dltdojo.org/cd23: dafu101
  name: ing101-nginxstable-alpine-c85e3d38
spec:
  minReadySeconds: 0
  progressDeadlineSeconds: 600
  replicas: 2
  selector:
    matchLabels:
      cdk8s.io/metadata.addr: ing101-nginxstable-alpine-c8007392
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        cdk8s.io/metadata.addr: ing101-nginxstable-alpine-c8007392
        dltdojo.org/cd23: dafu101
    spec:
      automountServiceAccountToken: false
      containers:
        - image: nginx:stable-alpine
          imagePullPolicy: Always
          name: main
          ports:
            - containerPort: 80
          resources:
            limits:
              cpu: 1500m
              memory: 2048Mi
            requests:
              cpu: 1000m
              memory: 512Mi
          securityContext:
            allowPrivilegeEscalation: false
            privileged: false
            readOnlyRootFilesystem: false
            runAsNonRoot: false
          startupProbe:
            failureThreshold: 3
            tcpSocket:
              port: 80
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      securityContext:
        fsGroupChangePolicy: Always
        runAsNonRoot: true
      setHostnameAsFQDN: false
---
apiVersion: v1
kind: Service
metadata:
  labels:
    dltdojo.org/cd23: dafu101
  name: dev201
spec:
  externalIPs: []
  ports:
    - port: 80
  selector:
    cdk8s.io/metadata.addr: ing101-nginxstable-alpine-c8007392
  type: ClusterIP
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    io.cilium.ingress/insecure-node-port: "32080"
    io.cilium.ingress/loadbalancer-mode: dedicated
    io.cilium.ingress/service-type: NodePort
  labels:
    dltdojo.org/cd23: dafu101
  name: ing101-ing-c80aaa38
spec:
  defaultBackend:
    service:
      name: dev101
      port:
        number: 80
  ingressClassName: cilium
  rules:
    - host: dev101.default.svc
      http:
        paths:
          - backend:
              service:
                name: dev101
                port:
                  number: 80
            path: /
            pathType: Prefix
    - host: dev201.default.svc
      http:
        paths:
          - backend:
              service:
                name: dev201
                port:
                  number: 80
            path: /
            pathType: Prefix
