apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: keycloak-postgresql
  namespace: keycloak
spec:
  volumeClaimTemplates:
    - metadata:
        name: data
      spec:
        storageClassName: local-path-retain
        accessModes:
          - "ReadWriteOnce"
        resources:
          requests:
            storage: "7Gi"