apiVersion: batch/v1
kind: Job
metadata:
  name: buildkit108
spec:
  template:
    spec:
      restartPolicy: Never
      initContainers:
        - name: prepare
          image: alpine:3.10
          command:
            - sh
            - -c
            - "echo FROM hello-world > /workspace/Dockerfile"
          volumeMounts:
            - name: workspace
              mountPath: /workspace
      containers:
        - name: buildkit
          image: moby/buildkit:v0.10.6
          command:
            - buildctl-daemonless.sh
          args:
            - build
            - --frontend
            - dockerfile.v0
            - --local
            - context=/workspace
            - --local
            - dockerfile=/workspace
            # 
            # out-cluster: k3d-registry101.localhost:12345
            # in-cluster: host.k3d.internal:5000
            - --output
            - type=image,name=k3d-registry101.localhost:12345/mybox:v1.2,push=true,registry.insecure=true
          securityContext:
            privileged: true
          volumeMounts:
            - name: workspace
              readOnly: true
              mountPath: /workspace
      volumes:
        - name: workspace
          emptyDir: {}