apiVersion: batch/v1
kind: Job
metadata:
  labels:
    kaniko.build/repo: hellok8s
    kaniko.build/tag: 0.1.5-denoapk
  name: c101-job221-c8c286fc
spec:
  activeDeadlineSeconds: 300
  template:
    metadata:
      labels:
        cdk8s.io/metadata.addr: c101-job221-c88111d3
    spec:
      automountServiceAccountToken: false
      containers:
        - args:
            - --dockerfile=Dockerfile
            - --destination=registry.local:5001/hellok8s:0.1.5-denoapk
            - --context=/worksapce
            - --insecure
            - --cache=true
            - --verbosity=debug
            - --reproducible
          image: gcr.io/kaniko-project/executor:latest
          imagePullPolicy: Always
          name: main
          resources:
            limits:
              cpu: 1500m
              memory: 2048Mi
            requests:
              cpu: 1000m
              memory: 512Mi
          securityContext:
            allowPrivilegeEscalation: false
            privileged: false
            readOnlyRootFilesystem: false
            runAsNonRoot: false
          volumeMounts:
            - mountPath: /workspace
              name: workspace
      dnsPolicy: ClusterFirst
      initContainers:
        - command:
            - sh
            - -c
            - |
              #!/bin/sh
              id
              env
              date
              pwd
              cat <<EOF > /workspace/Dockerfile
              # docker file
              FROM denoland/deno:alpine-1.31.1
              RUN apk add --no-cache git openssl sed curl jq busybox-extras
              EOF
          image: busybox:1.36
          imagePullPolicy: Always
          name: init-0
          resources:
            limits:
              cpu: 1500m
              memory: 2048Mi
            requests:
              cpu: 1000m
              memory: 512Mi
          securityContext:
            allowPrivilegeEscalation: false
            privileged: false
            readOnlyRootFilesystem: true
            runAsNonRoot: false
          volumeMounts:
            - mountPath: /workspace
              name: workspace
      restartPolicy: Never
      securityContext:
        fsGroupChangePolicy: Always
        runAsNonRoot: true
      setHostnameAsFQDN: false
      volumes:
        - emptyDir: {}
          name: workspace
  ttlSecondsAfterFinished: 300
