apiVersion: apps/v1
kind: Deployment
metadata:
  name: c101-traefik-whoamiv1.8.7-c8a75220
spec:
  minReadySeconds: 0
  progressDeadlineSeconds: 600
  replicas: 2
  selector:
    matchLabels:
      cdk8s.io/metadata.addr: c101-traefik-whoamiv1.8.7-c881baa7
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        cdk8s.io/metadata.addr: c101-traefik-whoamiv1.8.7-c881baa7
    spec:
      automountServiceAccountToken: false
      containers:
        - image: traefik/whoami:v1.8.7
          imagePullPolicy: Always
          name: main
          ports:
            - containerPort: 80
          resources:
            limits:
              cpu: 100m
              memory: 64Mi
            requests:
              cpu: 50m
              memory: 32Mi
          securityContext:
            allowPrivilegeEscalation: false
            privileged: false
            readOnlyRootFilesystem: false
            runAsNonRoot: false
          startupProbe:
            failureThreshold: 3
            tcpSocket:
              port: 80
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      securityContext:
        fsGroupChangePolicy: Always
        runAsNonRoot: true
      setHostnameAsFQDN: false
---
apiVersion: v1
kind: Service
metadata:
  name: dev101
spec:
  externalIPs: []
  ports:
    - port: 80
  selector:
    cdk8s.io/metadata.addr: c101-traefik-whoamiv1.8.7-c881baa7
  type: ClusterIP
