apiVersion: kind.x-k8s.io/v1alpha4
kind: Cluster
name: kind200
nodes:
  - role: control-plane
    image: >-
      kindest/node:1.25.3@sha256:f52781bc0d7a19fb6c405c2af83abfeb311f130707a0e219175677e366cc45d1
  - role: worker
    image: >-
      kindest/node:1.25.3@sha256:f52781bc0d7a19fb6c405c2af83abfeb311f130707a0e219175677e366cc45d1
containerdConfigPatches:
  - |-
    [plugins."io.containerd.grpc.v1.cri".registry.mirrors."registry.local:5001"]
      endpoint = ["http://registry.local:5001"]
