apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: vault
  namespace: vault
spec:
  updateStrategy:
    #
    # rollout status is only available for RollingUpdate strategy type
    #
    type: RollingUpdate
  volumeClaimTemplates:
    - metadata:
        name: data
      spec:
        storageClassName: local-path-retain
        accessModes:
            - "ReadWriteOnce"
        resources:
          requests:
            storage: "512Mi"
  template:
    spec:
      containers:
        - name: vault
          image: public.ecr.aws/docker/library/vault:1.9.2
          env:
            - name: VAULT_DEV_ROOT_TOKEN_ID
              value: null
              valueFrom:
                secretKeyRef:
                  name: vault-dev-token
                  key: token
          args: 
          - |
            date
            cat << EOF > /tmp/vault.hcl
            storage "file" {
              path = "/data"
            }
            EOF
            # [persistent dev mode · Issue #12004 · hashicorp/vault](https://github.com/hashicorp/vault/issues/12004)
            /usr/local/bin/docker-entrypoint.sh vault server -dev -config=/tmp/vault.hcl
          volumeMounts:
            - name: data
              mountPath: /data
