apiVersion: v1
kind: Service
metadata:
  name: keycloak-http
spec:
  ports:
    - name: https
      port: 8443
      targetPort: https
      protocol: TCP
      $patch: delete
    - name: https
      port: 443
      targetPort: https
      protocol: TCP