apiVersion: v1
kind: Secret
metadata:
  name: gitea
type: Opaque
stringData:
  app.ini: |-

    [cache]
    ADAPTER = memcache
    ENABLED = true
    HOST = gitea-memcached.gitea.svc.cluster.local:11211

    [database]
    DB_TYPE = postgres
    HOST = gitea-postgresql.gitea.svc.cluster.local:5432
    NAME = gitea
    PASSWD = gitea
    USER = gitea

    [metrics]
    ENABLED = false

    [repository]
    ROOT = /data/git/gitea-repositories

    [security]
    INSTALL_LOCK = true

    [server]
    APP_DATA_PATH = /data
    DOMAIN = gitea.127.0.0.1.nip.io
    ENABLE_PPROF = false
    HTTP_PORT = 3000
    PROTOCOL = http
    ROOT_URL = https://gitea.127.0.0.1.nip.io:9443
    SSH_DOMAIN = gitea.127.0.0.1.nip.io
    SSH_LISTEN_PORT = 22
    SSH_PORT = 22