apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: argocd
# 
# 2022-1212
# curl -sL -o k301/argocd.yaml https://raw.githubusercontent.com/argoproj/argo-cd/v2.5.4/manifests/install.yaml
# 
resources:
  # 非線上依賴版本，一來可以檢視內容，二來避免遠端斷線無法重起，三來可以用 gitops 控管內容。
  # https://github.com/argoproj/argo-cd/manifests/cluster-install
  # - argocd.yaml
  #
  # 線上依賴版本
  - https://raw.githubusercontent.com/argoproj/argo-cd/v2.5.4/manifests/install.yaml
configMapGenerator:
  # https://github.com/argoproj/argo-cd/blob/v2.5.4/docs/operator-manual/argocd-cm.yaml
  - name: argocd-cm
    behavior: merge
    literals:
      - admin.enabled="true"
