version: "3.8"
services:
  box101:
    image: busybox:1.35.0-glibc
    command:
      - sh
      - -c 
      - |
        env
        mkdir -p /home/cgi-bin
        cat <<"ENND" > /home/cgi-bin/sed
        #!/bin/sh
        eval "$${QUERY_STRING//&/;}"
        echo "Content-type: text/plain; charset=utf-8"
        echo ""
        echo -n $$content | sed 's|root|foo|g'
        ENND
        chmod 700 /home/cgi-bin/sed
        httpd -fv -p 3000 -h /home &
        sleep 20
        exit
  box102:
    image: busybox:1.34.1
    command:
      - sh
      - -c 
      - |
        env
        mkdir -p /home/cgi-bin
        cat <<"ENND" > /home/cgi-bin/wc
        #!/bin/sh
        eval "$${QUERY_STRING//&/;}"
        echo "Content-type: text/plain; charset=utf-8"
        echo ""
        echo -n $$content | wc -m
        ENND
        chmod 700 /home/cgi-bin/wc
        httpd -fv -p 3000 -h /home &
        sleep 20
        exit
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.box102.rule=PathPrefix(`/box102`)"
      - "traefik.http.routers.box102.entrypoints=web"
      - "traefik.http.services.box102.loadbalancer.server.port=3000"
      - "traefik.http.middlewares.box102-stripprefix.stripprefix.prefixes=/box102"
      - "traefik.http.routers.box102.middlewares=box102-stripprefix@docker"
  box103:
    image: busybox:1.35.0-musl
    command:
      - sh
      - -c 
      - |
        env
        sleep 10
        cat <<"ENND" | tee foo.sh | sed 's!|!|_docker_compose_lifecycle_networking_|!g' 
        echo "T1"
        alias sed_sidecar_busybox='(read var1; wget -qO- "http://localhost:3700/cgi-bin/srv-sed?content=$$var1")'
        cat /etc/passwd | sed 's!bin!foo!g' | grep root | sed_sidecar_busybox
        echo
        echo "T2"
        cat /etc/passwd | sed 's!bin!foo!g' | grep root | tee /tmp/foo | sed_sidecar_busybox | wc -m
        alias wc_sidecar_busybox='(read var1; wget -qO- "http://localhost:3700/cgi-bin/srv-wc?content=$$var1")'
        alias wc_sidecar_nginx='(read var1; wget -qO- "http://localhost:3800/box102/cgi-bin/wc?content=$$var1")'
        alias wc_per_host_traefik='(read var1; wget -qO- "http://traefik:80/box102/cgi-bin/wc?content=$$var1")'
        echo "T3 sidecar busybox cgi-bin proxy"
        cat /etc/passwd | sed 's!bin!foo!g' | grep root | tee /tmp/foo | sed_sidecar_busybox | tee /tmp/foo2 | wc_sidecar_busybox
        echo "T4 sidecar nginx proxy"
        cat /etc/passwd | sed 's!bin!foo!g' | grep root | tee /tmp/foo | sed_sidecar_busybox | tee /tmp/foo2 | wc_sidecar_nginx
        echo "T5 per-host-network traefik proxy"
        cat /etc/passwd | sed 's!bin!foo!g' | grep root | tee /tmp/foo | sed_sidecar_busybox | tee /tmp/foo2 | wc_per_host_traefik
        ENND
        sh foo.sh
  box103-sidecar:
    image: busybox:1.35.0
    network_mode: "service:box103"
    command:
      - sh
      - -c 
      - |
        env
        mkdir -p /home/cgi-bin
        cat <<"ENND" > /home/cgi-bin/srv-wc
        #!/bin/sh
        eval "$${QUERY_STRING//&/;}"
        echo "Content-type: text/plain; charset=utf-8"
        echo ""
        #
        # https://en.wikipedia.org/wiki/Reverse_proxy
        # istio 5 tasks: Traffic Management, Security, Policy Enforcement, Observability and Extensibility
        #
        wget -qO- "http://box102:3000/cgi-bin/wc?content=$$content"
        ENND
        chmod 700 /home/cgi-bin/srv-wc
        cat <<"ENND" > /home/cgi-bin/srv-sed
        #!/bin/sh
        eval "$${QUERY_STRING//&/;}"
        echo "Content-type: text/plain; charset=utf-8"
        echo ""
        wget -qO- "http://box101:3000/cgi-bin/sed?content=$$content"
        ENND
        chmod 700 /home/cgi-bin/srv-sed
        httpd -fv -p 3700 -h /home &
        sleep 20
        exit
  box103-sidecar-nginx:
    image: nginx:1.23
    network_mode: "service:box103"
    command:
      - /bin/sh
      - -c
      - |
        sed  -i "s/worker_processes  auto;/worker_processes  1;/" /etc/nginx/nginx.conf
        cat /etc/nginx/nginx.conf
        sleep 5
        cat <<\EOF > /etc/nginx/conf.d/default.conf
        server {
          listen  3800;
          server_name  localhost;
          location /box101/ {
            proxy_pass http://box101:3000/;
          }
          location /box102/ {
            proxy_pass http://box102:3000/; # note the trailing slash here, it matters!
          }
        }
        EOF
        nginx -g "daemon on;"
        sleep 20
        exit
  traefik:
    image: traefik:v2.9
    command:
      #- "--log.level=DEBUG"
      - "--api.insecure=true"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entrypoints.web.address=:80"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"