apiVersion: v1
kind: ConfigMap
metadata:
  name: argocd-cmd-params-cm # https://github.com/argoproj/argo-cd/blob/v2.1.7/docs/operator-manual/argocd-cmd-params-cm.yaml
data:
  ## Server properties
  # Run server without TLS
  server.insecure: "true"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: argocd-cm
data:
  url: https://argocd.127.0.0.1.nip.io:9443
  oidc.config: |
    name: keycloak
    issuer: http://keycloak-http.keycloak.svc.cluster.local/auth/realms/foo
    clientID: argocd101
    clientSecret: rACFQorPGrHcEhVgDsSpHFYrKfFwaS7b
    requestedScopes: ["openid", "profile", "email", "groups"]
    requestedIDTokenClaims: {"groups": {"essential": true}}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: argocd-rbac-cm
data:
  policy.csv: |
    g, ArgoCDAdmins, role:admin