services:
  app101:
    build:
      context: .
      dockerfile: Dockerfile
    #
    # docker compose run --rm app101
    #
    command: 
      - /bin/bash
      - /app/app.sh
    working_dir: /app
    volumes:
      - ./app.sh:/app/app.sh:ro