version: "3.8"
services:
  deno103:
    image: denoland/deno:1.29.1
    command:
      - sh
      - -c 
      - |
        env
        cd /app
        deno run --allow-net --allow-read --allow-env main.ts &
        sleep 3
        date
        echo "start http://localhost:8300"
        wait
    volumes:
      - ./d103.ts:/app/main.ts:ro
      - ./d103-tpl.ts:/app/d103-tpl.ts:ro
    ports:
      - 8300:3000