apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: gitea
spec:
  volumeClaimTemplates:
    - metadata:
        name: data
      spec:
        storageClassName: local-path-retain
        accessModes:
          - "ReadWriteOnce"
        resources:
          requests:
            storage: "5Gi"
  template:
    spec:
      initContainers:
        - name: init-directories
          image: docker.io/gitea/gitea:1.15.9
        - name: configure-gitea
          image: docker.io/gitea/gitea:1.15.9
      containers:
        - name: gitea
          image: docker.io/gitea/gitea:1.15.9
          volumeMounts:
            - name: cm-ca-nip
              mountPath: /etc/ssl/certs/ca-nip.crt
              subPath: ca.crt
      volumes:
        - name: cm-ca-nip
          configMap:
            name: ca-nip
            defaultMode: 420