apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: gitea
spec:
  volumeClaimTemplates:
    - metadata:
        name: data
      spec:
        storageClassName: local-path-retain
        accessModes:
          - "ReadWriteOnce"
        resources:
          requests:
            storage: "5Gi"
  template:
    spec:
      initContainers:
        - name: init-directories
          image: docker.io/gitea/gitea:1.15.8
        - name: configure-gitea
          image: docker.io/gitea/gitea:1.15.8
      containers:
        - name: gitea
          image: docker.io/gitea/gitea:1.15.8
