#
# docker compose up
# http://localhost:8300
#
services:
  box101:
    image: busybox:1.36.1
    command:
      - /bin/sh
      - -c
      - |
        env
        echo
        date
        echo
        mkdir /www
        cat <<\EOOF > /www/index.html
        <html>
          <head><title>busybox httpd 2024</title></head>
          <body><p>HELLO Busybox Httpd</p></body>
        </html>
        EOOF
        busybox httpd -f -v -p 3000 -h /www
    ports:
      - "8300:3000"
  # While many official images don't include SSH client, some do.  You might need SSH access within a container 
  # without the option of creating a custom Dockerfile (e.g., due to restrictions on building images). If you 
  # need SSH functionality and can't rebuild the image, you need to choose an image that already includes it.
  #
  box201:
    image: node:22.9
    command:
      - /bin/sh
      - -c
      - |
        env
        echo
        date
        echo
        sleep 9000
        # 
        # docker compose exec box2 bash
        # 
        # Exposing a local webserver via a public domain name, with automatic HTTPS
        # No installation, no signup
        # ssh -R 80:box101:3000 serveo.net
        # https://xxxxxx.serveo.net/
        # 
        # https://github.com/anderspitman/awesome-tunneling
