apiVersion: v1
kind: Service
metadata:
  name: opa101
  labels:
    app: opa101
spec:
  ports:
    - name: grpc
      port: 9191
      targetPort: 9191
  selector:
    app: opa101
---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: opa101
  labels:
    app: opa101
spec:
  replicas: 1
  selector:
    matchLabels:
      app: opa101
  template:
    metadata:
      labels:
        app: opa101
        version: 0.36.1-1
    spec:
      containers:
        - name: opa101
          image: docker.io/openpolicyagent/opa:0.36.1-istio-static
          securityContext:
            runAsUser: 1111
          volumeMounts:
            - readOnly: true
              mountPath: /policy
              name: opa-policy
          args:
            - "run"
            - "--server"
            - "--addr=localhost:8181"
            - "--diagnostic-addr=0.0.0.0:8282"
            - "--set=plugins.envoy_ext_authz_grpc.addr=:9191"
            - "--set=plugins.envoy_ext_authz_grpc.query=data.envoy.authz.allow"
            - "--set=decision_logs.console=true"
            - "--ignore=.*"
            - "/policy/policy.rego"
          ports:
            - containerPort: 9191
          resources: {}
          livenessProbe:
            httpGet:
              path: /health?plugins
              scheme: HTTP
              port: 8282
            initialDelaySeconds: 5
            periodSeconds: 5
          readinessProbe:
            httpGet:
              path: /health?plugins
              scheme: HTTP
              port: 8282
            initialDelaySeconds: 5
            periodSeconds: 5
      volumes:
        - name: opa-policy
          secret:
            secretName: opa101-policy
