apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: keycloak
secretGenerator:
  - name: keycloak-credentials
    literals:
      - username=keycloak-admin
      - password=1fJyRTcesfe2e67df123XYZ
resources:
  # 
  # [helm-charts/charts/keycloak at master · codecentric/helm-charts](https://github.com/codecentric/helm-charts/tree/master/charts/keycloak)
  # helm repo add codecentric https://codecentric.github.io/helm-charts
  # helm template keycloak codecentric/keycloak -n keycloak > keycloak.yaml
  - keycloak.yaml
patchesStrategicMerge:
  - patch-keycloak.yaml
  - patch-service.yaml
  - patch-postgresql.yaml
  - patch-vault-agent-inject.yaml