apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: keycloak
spec:
  template:
    metadata:
      labels: 
        version: 16.1.0-113
    spec:
      containers:
        - name: keycloak
          image: quay.io/keycloak/keycloak:16.1.0
          env:
            #
            # docker run -e KEYCLOAK_USER=<USERNAME> -e KEYCLOAK_PASSWORD=<PASSWORD> jboss/keycloak
            #
            #- name: KEYCLOAK_USER
            #  valueFrom:
            #    secretKeyRef:
            #      key:  username
            #      name: keycloak-credentials
            #- name: KEYCLOAK_PASSWORD
            #  valueFrom:
            #    secretKeyRef:
            #      key:  password
            #      name: keycloak-credentials
            - name: PROXY_ADDRESS_FORWARDING
              value: "true"
          volumeMounts:
            - mountPath: /etc/x509/https
              name: tls-config-volume
              readOnly: true
      volumes:
        - name: tls-config-volume
          secret:
            secretName: 127.0.0.1.sslip.io