apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  # 
  # helm repo add secrets-store-csi-driver https://kubernetes-sigs.github.io/secrets-store-csi-driver/charts
  # helm template csi-secrets-store secrets-store-csi-driver/secrets-store-csi-driver --namespace kube-system > csi-secret.yaml
  # 
  - csi-secret.yaml
