version: "3.8"
services:
  box1091:
    image: busybox:1.35.0
    command:
      - /bin/sh
      - -c
      - |
        cat <<EOOF > /etc/httpd.conf
        .wasm:application/wasm
        EOOF
        date
        busybox httpd -fv -p 3000 -c /etc/httpd.conf -h /home
    ports:
      - "8091:3000"
    volumes:
      - ./r105/pkg/r105_bg.wasm:/home/pkg/r105_bg.wasm:ro
      - ./r105/pkg/r105.js:/home/pkg/r105.js:ro
  box1092:
    image: busybox:1.35.0
    command:
      - /bin/sh
      - -c
      - |
        date
        busybox httpd -fv -p 3000 -h /home
    volumes:
      - ./r105/index.html:/home/index.html:ro
    ports:
      - "8092:3000"
  nginx101:
    image: nginx:1.23
    # cpu_count: 1
    command:
      - /bin/sh
      - -c
      - |
        sed  -i "s/worker_processes  auto;/worker_processes  1;/" /etc/nginx/nginx.conf
        cat /etc/nginx/nginx.conf
        sleep 5
        cat <<\EOF > /etc/nginx/conf.d/default.conf
        server {
          listen  80;
          server_name  localhost;
          location / {
            proxy_pass http://box1092:3000;
          }
          location /pkg {
            proxy_pass http://box1091:3000;
          }
        }
        EOF
        echo "Testing endpoint is http://localhost:8702"
        nginx -g "daemon off;"
    ports:
      - "8702:80"