services:
  #
  # http://localhost:8300/?folder=/home/workspace
  # 
  gitpod-openvscode-server:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8300:3000
    volumes:
      - ./banking.sh:/home/workspace/banking-readonly.sh:ro