apiVersion: v1
kind: ConfigMap
metadata:
  name: argocd-cm
data:
  url: https://argocd.127.0.0.1.nip.io:9443
  oidc.config: |
    name: vault
    issuer: http://oidc404.vault.svc.cluster.local/v1/identity/oidc/provider/pro101
    clientID: WCHi5G99psbLLpS0GHFnrHWCfx8m19bB
    clientSecret: hvo_secret_1d2kwqueEFNRM2buZHlFkO2np8DmQju36d3jKsziN7HC1tFiyTcoafVM5UIgLabD
    requestedScopes: ["openid", "user" , "groups"]
    requestedIDTokenClaims: {"groups": {"essential": true}}