[package]
name = "r105"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]
[dependencies]
wasm-bindgen = "0.2.83"
tiny-bip39 = "1.0.0"
getrandom = { version = "0.2", features = ["js"] }

[workspace]