default: test

test:
  cargo test

#
# [zellij-org/zellij: A terminal workspace with batteries included](https://github.com/zellij-org/zellij)
# zellij watch
watch:
  zellij --layout-path zellij.yaml

devserver-jsbind:
  devserver --address 127.0.0.1:8001 --path jsbind

devserver-docs:
  devserver --address 127.0.0.1:8002 --path docs/gen

dev-ui:
  cd app-ui && trunk serve

watch-wasi:
  cargo watch -- just test-wasi

build-jsbind:
  cd jsbind && wasm-pack build --target web

test-jsbind: build-jsbind
  cargo test -p jsbind
  deno test examples/deno/jsbind --allow-read

build-wapp:
  cargo build -p wapp

build-wapp-wasi:
  cargo test
  cargo build -p wapp --target wasm32-wasi

test-wasi: build-wapp-wasi
  wasmtime target/wasm32-wasi/debug/wapp.wasm -- -h
  # deno run -A examples/deno/jsbind.ts

build:
  echo Building

jsdoc:
  jsdoc -c docs/jsdoc.json

install-dev-deps:
  cargo install cargo-watch
  cargo install zellij
  cargo install trunk
  cargo install wasm-pack
  cargo install devserver
  cargo install mdbook
  npm i -g jsdoc

install-deno:
  # [Verify checksum of static lib in build script · Issue #545 · denoland/rusty_v8](https://github.com/denoland/rusty_v8/issues/545)
  # cargo install deno --locked --version 1.19.2
  curl -fsSL https://deno.land/x/install/install.sh | sh
  mv $HOME/.deno/bin/deno $HOME/.cargo/bin/deno
  deno --version

build-docker img="localdev14865/napp004" version="v0.1.0":
  docker build -t {{img}}:{{version}} .

k3d-import cluster="foo101" img="localdev14865/napp004" version="v0.1.0":
  docker build -t {{img}}:{{version}} .
  k3d image import {{img}}:{{version}} -c {{cluster}}