apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: vault
secretGenerator:
- literals:
  - token=ne34Rth000ared12buiSSing 
  name: vault-dev-token
  type: Opaque
resources:
  #
  # https://github.com/hashicorp/vault-helm
  # https://learn.hashicorp.com/tutorials/vault/kubernetes-secret-store-driver?in=vault/kubernetes
  # helm template vault hashicorp/vault -n vault --set "server.dev.enabled=true" --set "injector.enabled=false" --set "csi.enabled=false" > vault.yaml
  # dev token is root
  - vault.yaml
patchesStrategicMerge:
  - remove-test.yaml
  - img-env-dev-token.yaml