#
# [Grafana 8.3.1, 8.2.7, 8.1.8, and 8.0.7 released with high severity security fix | Grafana Labs](https://grafana.com/blog/2021/12/07/grafana-8.3.1-8.2.7-8.1.8-and-8.0.7-released-with-high-severity-security-fix/)
# upstream [Bump addon versions by howardjohn · Pull Request #36438 · istio/istio](https://github.com/istio/istio/pull/36438/files)
#
apiVersion: apps/v1
kind: Deployment
metadata:
  name: grafana
  namespace: istio-system
spec:
  template:
    metadata:
      labels:
        sidecar.istio.io/inject: "true"
        version: 8.3.3-9
    spec:
      containers:
        - name: grafana
          image: docker.io/grafana/grafana:8.3.3
          env:
            - name: "GF_AUTH_ANONYMOUS_ENABLED"
              value: "false"
            - name: GF_AUTH_GENERIC_OAUTH_CLIENT_ID
              valueFrom:
                secretKeyRef:
                  name: oidc-credentials
                  key: client-id
            - name: GF_AUTH_GENERIC_OAUTH_CLIENT_SECRET
              valueFrom:
                secretKeyRef:
                  name: oidc-credentials
                  key: client-secret
