apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-git-curl
  namespace: default
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: local-path-retain
  resources:
    requests:
      storage: 64Mi