apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: vault
  namespace: vault
spec:
  template:
    spec:
      containers:
        - name: vault
          image: public.ecr.aws/docker/library/vault:1.9.1
          env:
            - name: VAULT_DEV_ROOT_TOKEN_ID
              value: null
              valueFrom:
                secretKeyRef:
                  name: vault-dev-token
                  key: token