apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
#
# [Istio / Metrics](https://istio.io/latest/docs/tasks/observability/metrics/)
# curl -sLO https://raw.githubusercontent.com/istio/istio/release-1.12/samples/addons/grafana.yaml
# curl -sLO https://raw.githubusercontent.com/istio/istio/release-1.12/samples/addons/kiali.yaml
# curl -sLO https://raw.githubusercontent.com/istio/istio/release-1.12/samples/addons/prometheus.yaml
# curl -sLO https://raw.githubusercontent.com/istio/istio/release-1.12/samples/addons/jaeger.yaml
#
resources:
  - grafana.yaml
  - kiali.yaml
  - prometheus.yaml
  - jaeger.yaml
patchesStrategicMerge:
  #
  # Grafana 8.3.1, 8.2.7, 8.1.8, and 8.0.7 released with high severity security fix | Grafana Labs
  # https://grafana.com/blog/2021/12/07/grafana-8.3.1-8.2.7-8.1.8-and-8.0.7-released-with-high-severity-security-fix/
  #
  # TODO [Bump addon versions by howardjohn · Pull Request #36438 · istio/istio](https://github.com/istio/istio/pull/36438/files)
  # 
  - grafana-fix-8.3.1.yaml
  - grafana-oidc.yaml
  #
  # kiali Configure External Services : Grafana https://github.com/kiali/kiali#grafana
  # https://grafana-istio-system.127.0.0.1.nip.io:9443
  # 效果不明顯
  # - patch-kiali-grafana-url.yaml
