apiVersion: v1
kind: ConfigMap
metadata:
  name: argocd-cmd-params-cm # https://github.com/argoproj/argo-cd/blob/v2.1.7/docs/operator-manual/argocd-cmd-params-cm.yaml
data:
  ## Server properties
  # Run server without TLS
  server.insecure: "true"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: argocd-cm
data:
  url: https://argocd.127.0.0.1.nip.io:9443
  oidc.config: |
    name: keycloak
    issuer: https://keycloak.127.0.0.1.nip.io:9443/auth/realms/pro101
    clientID: client101
    clientSecret: e8mgccZOA4Jx7EGO4HdhAxAu99icDQkp
    requestedScopes: ["openid"]
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: argocd-rbac-cm
data:
  policy.csv: |
    g, argocd-admin, role:admin