version: "3.8"
services:
  githttp201:
    build:
      context: .
      target: busybox101
    entrypoint: sh
    command:
      - -c
      - |
        env
        id
        git config --global user.email "foo1001@testing.local"
        git config --global user.name "FooName1001"
        mkdir -p /app/repo/foo
        cd /app/repo/foo
        echo $(date) > README.md
        git init -q
        git add .
        git commit -m 'init commit'
        curl -sv --retry 10 --retry-all-errors http://githttp101:8080/
        git remote add upstream101 http://githttp101:8080/foo
        git remote -v
        git pull
        git push --set-upstream upstream101 master
  githttp101:
    build:
      context: .
      target: web168-git105
    entrypoint: sh
    command:
      - -c
      - |
        env
        id
        mkdir -p /app/repo/foo
        git config --system http.receivepack true
        git config --system http.uploadpack true
        git config --system user.email "gitserver@dev.local"
        git config --system user.name "Git Server"
        git config --global user.email "you@example.com"
        git config --global user.name "Your Name"
        mkdir -p /app/repo/foo; cd /app/repo/foo &&  git init --bare -q && echo "foo project 1234" > description
        cd /app/repo/foo
        ls -alh
        git branch
        echo "git instaweb /app/repo/foo to port 1234 and mapping to http://localhost:9080"
        cd /app/repo/foo &&  git instaweb
        echo "golang version of git-http-backend start at :8080"
        echo "git remote add upstream101 http://githttp101:8080/foo"
        go-git-http-backend --project_root=/app/repo --git_bin_path=/usr/bin/git -server_address=":8080"
    ports:
      - 9080:1234