version: "3.8"
services:
  dev101:
    image: busybox:1.35.0
    command:
      - /bin/sh
      - -c
      - |
        env
        cd /home
        TODAY=$(date)
        cat <<EOF > /home/index.html
        <html>
        <head><title>Web Dev Stack Testing</title></head>
        <body><h1>WebDev Stack 101 $$TODAY</h1>
        <h2><a href="/page.html">page</a></h2>
        </body>
        </html>
        EOF
        cat <<EOF > /home/page.html
        <html>
        <head><title>Page: Web Dev Stack</title></head>
        <body><h1>Page: WebDev Stack 101 $$TODAY</h1></body>
        </html>
        EOF
        # busybox httpd -fv -p 3000 -h /home
        httpd -fv -p 3000 -h /home
    ports:
      - 8300:3000
  dev102:
    image: curlimages/curl
    command:
      - /bin/sh
      - -c
      - |
        env
        curl -sv --retry 10 --retry-all-errors http://dev101:3000/
        curl -sv http://dev101:3000/page.html