apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-nginx2
  labels:
    app: my-nginx2
spec:
  selector:
    matchLabels:
      run: my-nginx2
  replicas: 2
  template:
    metadata:
      labels:
        run: my-nginx2
    spec:
      containers:
        - name: my-nginx2
          image: public.ecr.aws/docker/library/nginx:1.21
          ports:
            - containerPort: 80
          resources:
            limits:
              cpu: "1"
              memory: 256Mi
            requests:
              cpu: 200m
              memory: 128Mi
---
apiVersion: v1
kind: Service
metadata:
  name: my-nginx2
  labels:
    run: my-nginx2
    app: my-nginx2
spec:
  ports:
    - port: 80
      protocol: TCP
      name: http-web
  selector:
    run: my-nginx2
