apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: argocd
# 2021-1221
# curl -sL -o argocd.yaml https://raw.githubusercontent.com/argoproj/argo-cd/v2.2.1/manifests/install.yaml
# 
resources:
  - argocd.yaml
  # 避免使用線上依賴版本，一來可以檢視內容，二來避免遠端斷線無法重起，三來可以用 gitops 控管內容。
  # - https://github.com/argoproj/argo-cd/manifests/cluster-install
  #
patchesStrategicMerge:
  #
  # [Argo CD Istio deploy compatibility · Issue #2784 · argoproj/argo-cd](https://github.com/argoproj/argo-cd/issues/2784)
  #
  - patch-insecure.yaml