version: "3.8"
services:
  boxk8s1:
    image: api101-k8sapi
    command:
      - /bin/sh
      - -c
      - |
        cd /opt/webroot/api-ui/
        busybox httpd -f -v -p 3000
    ports:
      - "8300:3000"
  boxk8s2:
    image: api101-k8sapi
    command:
      - /bin/sh
      - -c
      - |
        cd /opt/webroot/api-ui/
        busybox httpd -f -v -p 3000
    ports:
      - "8310:3000"
  krakend:
    image: devopsfaith/krakend:2.1.2
    entrypoint: /bin/sh
    command:
      - -c
      - |
        cat > /tmp/krakend.yaml <<\EOOF
        version: 3
        endpoints:
        - endpoint: "/box1/{path1}"
          output_encoding: no-op
          method: GET
          backend:
          - host:
            - http://boxk8s1:3000
            method: GET
            url_pattern: "/{path1}"
            encoding: no-op
        - endpoint: "/box2/{path1}"
          output_encoding: no-op
          method: GET
          backend:
          - host:
            - http://boxk8s2:3000
            method: GET
            url_pattern: "/{path1}"
            encoding: no-op
        EOOF
        /usr/bin/krakend run -c /tmp/krakend.yaml
    ports:
      - "8320:8080"