# syntax=docker/dockerfile:1.3-labs
FROM busybox:1.35.0 AS stage1
ARG SWAGGER_UI_VERSION="4.15.2"
RUN <<\EOOF
  cd /tmp
  wget "https://github.com/swagger-api/swagger-ui/archive/v$SWAGGER_UI_VERSION.zip"
  unzip "v$SWAGGER_UI_VERSION.zip" -d swagger-ui
  mkdir -p /opt/webroot/api-ui
  cp -r "swagger-ui/swagger-ui-$SWAGGER_UI_VERSION/dist/." /opt/webroot/api-ui/
EOOF
FROM stage1 AS stage2
RUN <<\EOOF
  wget -O /opt/webroot/api-ui/swagger.json https://github.com/kubernetes/kubernetes/raw/release-1.25/api/openapi-spec/swagger.json
  sed -i "s|https://petstore.swagger.io/v2/swagger.json|swagger.json|g" /opt/webroot/api-ui/swagger-initializer.js
EOOF