version: "3.8"
services:
  box101:
    image: api101-busybox
    command:
      - /bin/sh
      - -c
      - |
        cd /opt/webroot/api-ui/
        # sed -i "s|https://petstore.swagger.io/v2/swagger.json|spec-foo.json|g" /opt/webroot/api-ui/swagger-initializer.js
        busybox httpd -f -v -p 3000
    ports:
      - "8300:3000"