@startuml
hide footbox
participant "Local\nBusybox" as Local
actor Alice
participant "Online\nPetstore" as Petstore
autonumber 10
Local -> Alice : swagger-ui
autonumber 20
Alice <- Petstore : swagger.json
@enduml