version: "3.8"
services:
  opa101:
    image: openpolicyagent/opa:0.46.1-debug
    ports:
    - 8181:8181
    entrypoint: sh
    command:
    - -c
    - |
      cat <<EOF > /tmp/policy.rego
      package httpapi.authz
      # mapping to uri /v1/data/httpapi/authz
      default allow = false
      allow {
          input.X_FORWARDED_URI == "/foo.html"
          input.method == "GET"
      }
      EOF
      opa run -s /tmp/policy.rego
  deno101:
    build:
      context: .
      target: deno101
    entrypoint: sh
    command:
      - -c 
      - |
        cat <<\EOOF > webserver.ts
        import { serve } from "https://deno.land/std@0.163.0/http/server.ts";
        const handler = async (req: Request): Promise<Response> => {
          const url = new URL(req.url);
          const input = {
            method: req.method,
            path: url.pathname,
            X_FORWARDED_URI: req.headers.get("x-forwarded-uri"),
          };
          console.log(input);
          const body = JSON.stringify({input});
          const resp = await fetch("http://opa101:8181/v1/data/httpapi/authz", {
            method: "POST",
            headers: {"Content-Type": "application/json",},
            body,
          });
          let finalresp = new Response("Auth Error 201",{status:404});
          if (resp.body) {
            const r = await resp.json();
            console.log("OPA Resp = ", r);
            finalresp =  r.result["allow"] ? new Response("OK") : new Response("Auth Error 301",{status: 403});
          }
          console.log(finalresp);
          return finalresp;
        };
        await serve(handler, { port:8080});
        EOOF
        deno run --allow-net webserver.ts
    ports:
      - "8303:8080"
  box1:
    image: curlimages/curl:7.86.0
    command:
      - sh
      - -c
      - |
        sleep 5
        curl -sv http://deno101:8080
        curl -sv --header "x-forwarded-uri: /foo.html" http://deno101:8080
    ports:
      - "8301:3000"
  deno201:
    build:
      context: .
      target: deno101
    entrypoint: sh
    command:
      - -c 
      - |
        cat <<\EOOF > test.ts
        import chai from "https://esm.sh/chai@4.3.6";
        const resp1 = await fetch("http://deno101:8080", {
            method: "GET",
            headers: {"x-forwarded-uri": "/foo.html"}
          });
        chai.assert.equal(200, resp1.status);
        const resp2 = await fetch("http://deno101:8080");
        chai.assert.equal(403, resp2.status);
        EOOF
        sleep 10
        deno run --allow-net test.ts