version: "3.8"
services:
  deno104:
    image: denoland/deno:1.29.1
    command:
      - sh
      - -c 
      - |
        env
        cd /app
        deno run -A - <<"END"
        import { prepareVirtualFile } from "https://deno.land/x/mock_file@$VERSION/mod.ts";
        const content = new TextEncoder().encode("hello world");
        prepareVirtualFile("./no/such/file.txt", content);
        const file = Deno.openSync("./no/such/file.txt");
        END
    volumes:
      - .:/app:ro
    ports:
      - 8903:8000