apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: gitea
# gitea [gitea/helm-chart: Helm chart for gitea - helm-chart - Gitea: Git with a cup of tea](https://gitea.com/gitea/helm-chart/)
# helm repo add gitea-charts https://dl.gitea.io/charts/
# helm repo update
# without existingClaim
# helm template gitea gitea-charts/gitea -n gitea -f helm-value.yaml > gitea.yaml
resources:
  - gitea.yaml
  - gitea-sa.yaml
#
# [Ability to disable hash suffix for generated secrets and configmaps. · Issue #50 · kubernetes-sigs/kustomize](https://github.com/kubernetes-sigs/kustomize/issues/50)
#
secretGenerator:
  #
  # 注意：如有 vault 注入該設定無效
  # gitea-credentials 除了預設在 helm 建立 --set gitea.admin.existingSecret=gitea-credentials 之外
  # ？？？ 還會應用到 git-repo-push-job (不在 kustomize 範圍) 上，需固定不能加上後綴，失去後綴缺點是執行 gitea-credentials 更新要手動重起生效。
  - name: gitea-credentials
    literals:
      - username=gitea-admin101
      - password=1fJyRTcesfe2e67df123XYZ
    options:
      disableNameSuffixHash: true
patchesStrategicMerge:
  # 坑
  # 這 gitea-test-connection pod 因 label 設計與 gitea 一樣
  # 這樣會被 gitea-http.svc 的 selector 選上造成混亂無法用 curl -v http://gitea-http.gitea.svc.cluster.local:3000
  # 但是從 istio-ingressgateway 進來的卻不受影響，可是 argocd 需要使用內部網址必須將這個衝突去掉，可以改 label 或是直接刪除
  # 不用 kiali 實在看不出來這種問題，直接拿 helm 輸出來改要注意。
  - remove-test-connection.yaml
  #
  # volumeClaimTemplates/spec/volumeName 預設沒有會自動建一個 PV
  # 一旦開始後需要轉為 prod 綁定 PV 否則會每次用全新增的 PV
  - patch-gitea-postgresql.yaml
    #
    # 對外的 ROOT_URL = https://gitea-127-0-0-1.nip.io:9443 需要覆寫
    #
  - patch-gitea.yaml
  - patch-inline-config.yaml
  # 
  # [The order of initContainers changed after the patch · Issue #3912 · kubernetes-sigs/kustomize](https://github.com/kubernetes-sigs/kustomize/issues/3912)
  #
  - patch-vault-agent-inject.yaml
